# Railway Configuration for Backend
[build]
builder = "DOCKERFILE"
dockerfilePath = "BE-HR-main/Dockerfile"

[deploy]
startCommand = "/usr/local/bin/docker-entrypoint.sh"
healthcheckPath = "/api/ping"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Tell Railway which port the HTTP server (Nginx) listens on
[service]
port = 8080
