services:
  - type: web
    name: hr-be
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:P0gI9VtmU5O0/0XI2o/NC7NeYzsKVOTpuEwdJiAXAvk=
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://hr-be.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: HR-BE
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: log
      - key: MAIL_HOST
        value: 127.0.0.1
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel
