# Railway Configuration for Frontend
[build]
builder = "DOCKERFILE"
dockerfilePath = "FE-HR-main/Dockerfile"

[deploy]
healthcheckPath = "/test-api"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Tell Railway which port the HTTP server (Nginx) listens on
[service]
port = 8080
